apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-builder-1
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/sustainatrade/frontend
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: incr3m/test-knative-kaniko
